/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.torguet.projetgui;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author Patrice Torguet
 */
public class HelpDialog extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form HelpDialog
     */
    public HelpDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
        
        this.setTitle("Aide");
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Aide du logiciel\n\nIci nous pourrons écrire les informations sur l'aide.\n\nLa zone de texte pouvant contenir un texte très long.\n\nInsérons un texte quelconque grâce à https://www.lipsum.com/\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vitae dolor in ante vulputate laoreet. Etiam sit amet massa rhoncus, facilisis purus ac, facilisis enim. Nulla nec sapien porttitor, maximus mauris ac, interdum nisi. Integer nec leo a ligula sodales mattis. Donec imperdiet quam fermentum ligula molestie sagittis. Integer vestibulum odio et faucibus interdum. Sed est nibh, maximus ac hendrerit ac, finibus vitae mauris. Nunc interdum id tortor nec commodo. Fusce at sagittis augue, et auctor est. Etiam tellus velit, interdum vel interdum a, gravida in tortor. Proin malesuada, velit nec molestie pulvinar, dolor elit tincidunt enim, vel rutrum nisi nulla at elit. Donec porttitor eu tortor nec efficitur. Cras finibus sagittis neque, nec luctus lorem volutpat et. Phasellus volutpat at nisl quis fermentum. Nulla vulputate tincidunt risus. Nam porta, nisl in ullamcorper feugiat, turpis erat efficitur lectus, quis efficitur ex arcu vestibulum est.\n\nVivamus commodo sagittis congue. Vestibulum at nulla pretium, tincidunt urna quis, blandit augue. Suspendisse tristique elementum turpis vel mattis. Sed a placerat elit. Vestibulum porta sit amet ipsum sit amet lacinia. Donec nisl massa, sagittis id laoreet sit amet, tempus id nisi. Nunc nec condimentum orci. Etiam iaculis risus sed justo dapibus pulvinar in eget purus. In ullamcorper vitae neque vitae varius. Pellentesque consequat suscipit risus, elementum vulputate erat posuere nec. Ut accumsan bibendum mi, efficitur rhoncus ante posuere eu.\n\nIn sagittis vehicula felis nec suscipit. Fusce in volutpat augue. Quisque maximus quam non purus pretium, vel lacinia lorem vestibulum. Etiam aliquet non nisi molestie porttitor. Donec tempus, nunc at interdum commodo, urna lectus sodales diam, nec consequat purus metus id augue. Nam condimentum, erat cursus convallis iaculis, magna purus lacinia nisl, aliquet feugiat leo nunc nec massa. Mauris sed facilisis nulla.\n\nQuisque et urna felis. Duis orci nisi, tempor ac ultricies a, tincidunt eu turpis. Morbi ornare condimentum sapien, sed euismod magna mattis a. Morbi tempor auctor auctor. In nulla velit, lobortis eu ultrices non, sodales vitae ex. Nullam enim ante, pretium eget porttitor in, dapibus nec enim. Integer vel pretium felis. Donec egestas finibus lobortis. Phasellus fermentum ullamcorper pretium. Pellentesque lobortis dapibus ex, non lacinia turpis porttitor ac. Morbi tempor mauris quis erat luctus luctus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque pharetra commodo pulvinar.\n\nUt nulla felis, ultricies id massa quis, euismod porta ipsum. Nulla nec libero vitae ante bibendum fringilla. Curabitur vulputate faucibus ligula, ut porta dui maximus non. Mauris vitae lectus a nulla ultricies fermentum. Vivamus congue lacus at blandit lacinia. Donec est risus, dignissim ac auctor id, facilisis sit amet ipsum. Curabitur mollis diam eu venenatis suscipit. Duis quis diam gravida, porttitor est non, egestas magna. Donec eget sapien a metus ullamcorper ultrices sed eget sem. Ut nec tincidunt ante, a aliquet sapien. Sed consequat, felis nec lacinia rutrum, magna ex feugiat erat, sit amet porta massa libero non ligula. Vestibulum convallis erat vel justo semper, in scelerisque purus convallis. Curabitur non suscipit dui. Suspendisse mollis magna arcu.\n\nUt ultricies, elit non scelerisque rhoncus, dolor orci laoreet massa, quis blandit erat tellus a lorem. Donec turpis metus, posuere non condimentum nec, tincidunt in ipsum. Donec lacinia sem et leo tempus sagittis. Morbi eget convallis nisl. Aenean eu diam sit amet erat faucibus sodales id ut ex. Praesent auctor dictum facilisis. Sed a aliquet dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nullam quam urna, elementum ac est eu, placerat venenatis nisl. Quisque maximus quam velit, et lobortis elit blandit viverra. Nullam lacus neque, interdum sed pretium id, dictum quis felis. Donec pellentesque convallis lectus, nec mattis tortor dignissim eget.\n\nPraesent molestie, lorem vitae mollis semper, dui tortor eleifend lorem, sit amet iaculis mi libero a nisi. Nullam nec enim a urna consectetur fermentum. Vivamus pulvinar, erat id pretium vestibulum, est arcu imperdiet dui, id ullamcorper nulla eros ut nibh. Vivamus accumsan nisi sed ante dapibus, quis tempor lacus venenatis. Sed fermentum turpis at auctor molestie. Fusce nec purus vel nisl eleifend dictum hendrerit quis metus. Morbi consequat risus orci, ut aliquam augue laoreet nec. Etiam a mauris vitae tortor venenatis bibendum. Maecenas in metus id risus aliquet gravida. Suspendisse ut commodo est, nec porta ex. Fusce sed nibh eget lorem accumsan consequat. Suspendisse porta est sapien, aliquam malesuada dui elementum cursus. Aliquam erat volutpat. Ut non vulputate ipsum. Ut vitae ante turpis.\n\nPhasellus a felis porta, pulvinar odio ut, congue nibh. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse placerat lorem eu leo feugiat imperdiet. Sed ultricies, diam id ornare mollis, massa nisl hendrerit massa, eget consequat lacus nisi ac est. Nullam leo massa, fringilla euismod risus id, accumsan sodales est. Suspendisse vitae nulla et nisi scelerisque pharetra. Cras bibendum, sem dictum volutpat dignissim, ex odio tempor lorem, non commodo sapien ex vitae elit. Proin efficitur felis sit amet libero lacinia, at sollicitudin orci aliquet. Suspendisse tristique aliquam metus, non vehicula metus. Curabitur auctor elit nibh, quis porttitor nunc placerat commodo. Aliquam nec justo nisl. Maecenas at lacus vitae erat efficitur auctor. Duis eu mollis leo.\n\nSed aliquet suscipit urna. Etiam laoreet massa ac sapien interdum, ac tincidunt orci finibus. Pellentesque convallis neque nulla, vitae consequat turpis luctus non. Nunc maximus erat ut mauris rutrum, non maximus orci tristique. Sed pretium maximus magna. Suspendisse pretium nunc sem, iaculis aliquet augue mattis sit amet. Nulla pharetra quis purus ac sodales. Nunc ex lectus, finibus at bibendum non, iaculis et odio. Sed magna arcu, placerat in dolor in, viverra imperdiet lacus.\n\nPhasellus rhoncus eget erat sit amet posuere. Etiam et egestas tortor, ut facilisis augue. Vestibulum ut tellus a felis vestibulum bibendum dictum quis augue. Suspendisse in aliquam dolor. Aliquam erat volutpat. Pellentesque varius rutrum massa sed aliquam. Integer suscipit dui eget nisi suscipit, sed feugiat mi fermentum. Donec tristique velit molestie faucibus pulvinar. Praesent laoreet ultrices magna. Donec a sapien enim.\n\n10 paragraphes, 971 mots, 6513 caractères de Lorem Ipsum généré\n\n\n\n");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okButton)
                .addContainerGap())
        );

        getRootPane().setDefaultButton(okButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelpDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelpDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelpDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelpDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HelpDialog dialog = new HelpDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
